name: Claude OAuth

on:
  workflow_dispatch:
    inputs:
      code:
        description: 'Authorization code (leave empty for step 1)'
        required: false
  push:

permissions:
  actions: write  # Required for cache and artifacts
  contents: read  # Required for basic repository access

jobs:
  auth:
    runs-on: ubuntu-latest
    steps:
      - uses: grll/claude-code-login@v1

 - name: Upload Claude credentials as artifact
        uses: actions/upload-artifact@v4
        with:
          name: claude-credentials
          path: credentials.json
      
        with:
          code: ${{ inputs.code }}
          secrets_admin_pat: ${{ secrets.SECRETS_ADMIN_PAT }}

      # ✅ 追加：認証後の credentials.json を Artifact として保存
      - name: Upload Claude credentials as artifact
        uses: actions/upload-artifact@v4
        with:
          name: claude-credentials
          path: credentials.json
