name: Claude OAuth

on:
  workflow_dispatch:
    inputs:
      code:
        description: 'Authorization code (leave empty for step 1)'
        required: false

permissions:
  actions: write
  contents: read

jobs:
  auth:
    runs-on: ubuntu-latest
    steps:
      - name: Claude OAuth Login
        uses: grll/claude-code-login@v1
        with:
          code: ${{ inputs.code }}
          secrets_admin_pat: ${{ secrets.SECRETS_ADMIN_PAT }}

      - name: Upload Claude credentials as artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: claude-credentials
          path: credentials.json

      - name: Dump credentials.json to log
        if: success()
        run: |
          echo "===== BEGIN credentials.json ====="
          cat credentials.json
          echo "===== END credentials.json ====="
