name: Claude OAuth Login

on:
  workflow_dispatch:
    inputs:
      code:
        description: 'Step 2 で貼る認可コード（Step 1 では空欄）'
        required: false

permissions:
  actions: write    # cache / artifact / secrets
  contents: read

jobs:
  auth:
    runs-on: ubuntu-latest
    steps:
      #── Claude OAuth フロー（Step 1 / Step 2 共通）
      - name: Claude OAuth Login
        id: login
        uses: grll/claude-code-login@v1
        with:
          code: ${{ inputs.code }}
          secrets_admin_pat: ${{ secrets.SECRETS_ADMIN_PAT }}

      #── credentials.json の場所を特定
      - name: Locate credentials.json
        if: success()
        run: |
          FILE=$(find $GITHUB_WORKSPACE -name credentials.json | head -n1)
          if [ -z "$FILE" ]; then
            echo "❌ credentials.json not found"
            exit 1
          fi
          echo "CRED_PATH=$FILE" >> $GITHUB_ENV
          echo "credentials.json located at: $FILE"

      #── Artifact に添付
      - name: Upload credentials as artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: claude-credentials
          path: ${{ env.CRED_PATH }}

      #── ログにも出力（ペースト用）
      - name: Dump credentials.json to log
        if: success()
        run: |
          echo "===== BEGIN credentials.json ====="
          cat "$CRED_PATH"
          echo "===== END credentials.json ====="
